In [1]:
#import essential libraries 
import pandas as pd
import numpy as np
import dateutil.parser as parser
import json as json

In [25]:
#df load
data = pd.read_csv('/conservational-species-QLD.csv',encoding='cp1252')

In [26]:
data

,Taxon_Id,Kingdom,Class,Family,Scientific_name,Common_name,Taxon_author,NCA_status,EPBC_status,Significant,Confidential,Endemicity
0,706,animals,amphibians,Limnodynastidae,Adelotus brevis,tusked frog,"(Günther, 1863)",V,NaN,Y,N,QA
1,690,animals,amphibians,Limnodynastidae,Lechriodus fletcheri,black soled frog,"(Boulenger, 1890)",C,NaN,N,N,QA
2,677,animals,amphibians,Limnodynastidae,Limnodynastes convexiusculus,marbled frog,"(MacLeay, 1877)",C,NaN,N,N,QAI
3,678,animals,amphibians,Limnodynastidae,Limnodynastes dumerilii,grey bellied pobblebonk,"Peters, 1863",C,NaN,N,N,QA
4,679,animals,amphibians,Limnodynastidae,Limnodynastes fletcheri,barking frog,"Boulenger, 1888",C,NaN,N,N,QA
...,...,...,...,...,...,...,...,...,...,...,...,...
21752,25858,protozoans,slime molds,Physaraceae,Fuligo septica,NaN,(L.) F.H.Wigg.,C,NaN,N,N,Q
21753,34854,protozoans,slime molds,Stemonitidaceae,Comatricha pulchella,NaN,(Bab.) Rostaf.,C,NaN,N,N,Q
21754,27732,protozoans,slime molds,Stemonitidaceae,Stemonitis splendens,NaN,Rostaf.,C,NaN,N,N,Q
21755,41204,protozoans,slime molds,Trichiidae,Hemitrichia serpula,NaN,(Scop.) Rostaf.,C,NaN,N,N,Q
21756,34033,protozoans,slime molds,Tubiferaceae,Lycogala epidendrum,NaN,(L.) Fr.,C,NaN,N,N,Q

In [27]:
print ("data is ",data.shape)

data is  (21757, 12)

In [28]:
#rename the DwC terms
data = data.rename(columns=
{
'Taxon_Id':'taxonID',
'Kingdom':'kingdom',
'Class':'class',
'Family':'family',
'Scientific_name':'scientificName',
'Common_name': 'vernacularName',
'Taxon_author':'scientificNameAuthorship',
'NCA_status':'status',
'EPBC_status':'EPBCstatus',
'Significant':'conservationSignificant',
'Confidential':'confidential',
'Endemicity':'endemicity',
'Confidential':'confidential'
    
})

In [29]:
data

,taxonID,kingdom,class,family,scientificName,vernacularName,scientificNameAuthorship,status,EPBCstatus,conservationSignificant,confidential,endemicity
0,706,animals,amphibians,Limnodynastidae,Adelotus brevis,tusked frog,"(Günther, 1863)",V,NaN,Y,N,QA
1,690,animals,amphibians,Limnodynastidae,Lechriodus fletcheri,black soled frog,"(Boulenger, 1890)",C,NaN,N,N,QA
2,677,animals,amphibians,Limnodynastidae,Limnodynastes convexiusculus,marbled frog,"(MacLeay, 1877)",C,NaN,N,N,QAI
3,678,animals,amphibians,Limnodynastidae,Limnodynastes dumerilii,grey bellied pobblebonk,"Peters, 1863",C,NaN,N,N,QA
4,679,animals,amphibians,Limnodynastidae,Limnodynastes fletcheri,barking frog,"Boulenger, 1888",C,NaN,N,N,QA
...,...,...,...,...,...,...,...,...,...,...,...,...
21752,25858,protozoans,slime molds,Physaraceae,Fuligo septica,NaN,(L.) F.H.Wigg.,C,NaN,N,N,Q
21753,34854,protozoans,slime molds,Stemonitidaceae,Comatricha pulchella,NaN,(Bab.) Rostaf.,C,NaN,N,N,Q
21754,27732,protozoans,slime molds,Stemonitidaceae,Stemonitis splendens,NaN,Rostaf.,C,NaN,N,N,Q
21755,41204,protozoans,slime molds,Trichiidae,Hemitrichia serpula,NaN,(Scop.) Rostaf.,C,NaN,N,N,Q
21756,34033,protozoans,slime molds,Tubiferaceae,Lycogala epidendrum,NaN,(L.) Fr.,C,NaN,N,N,Q

In [30]:
#data = pd.concat([data2, data1])
data['taxonID'].count()

21757

In [31]:
data['status'].count()

18706

In [32]:
data = data[data['status'].notna()]
data['status'].count()

18706

In [33]:
data

,taxonID,kingdom,class,family,scientificName,vernacularName,scientificNameAuthorship,status,EPBCstatus,conservationSignificant,confidential,endemicity
0,706,animals,amphibians,Limnodynastidae,Adelotus brevis,tusked frog,"(Günther, 1863)",V,NaN,Y,N,QA
1,690,animals,amphibians,Limnodynastidae,Lechriodus fletcheri,black soled frog,"(Boulenger, 1890)",C,NaN,N,N,QA
2,677,animals,amphibians,Limnodynastidae,Limnodynastes convexiusculus,marbled frog,"(MacLeay, 1877)",C,NaN,N,N,QAI
3,678,animals,amphibians,Limnodynastidae,Limnodynastes dumerilii,grey bellied pobblebonk,"Peters, 1863",C,NaN,N,N,QA
4,679,animals,amphibians,Limnodynastidae,Limnodynastes fletcheri,barking frog,"Boulenger, 1888",C,NaN,N,N,QA
...,...,...,...,...,...,...,...,...,...,...,...,...
21752,25858,protozoans,slime molds,Physaraceae,Fuligo septica,NaN,(L.) F.H.Wigg.,C,NaN,N,N,Q
21753,34854,protozoans,slime molds,Stemonitidaceae,Comatricha pulchella,NaN,(Bab.) Rostaf.,C,NaN,N,N,Q
21754,27732,protozoans,slime molds,Stemonitidaceae,Stemonitis splendens,NaN,Rostaf.,C,NaN,N,N,Q
21755,41204,protozoans,slime molds,Trichiidae,Hemitrichia serpula,NaN,(Scop.) Rostaf.,C,NaN,N,N,Q
21756,34033,protozoans,slime molds,Tubiferaceae,Lycogala epidendrum,NaN,(L.) Fr.,C,NaN,N,N,Q

In [34]:
def replace_all(text, codes):
    for i, j in codes.items():
        text = text.replace(i, j)
    return text

In [35]:
codes = {
"EX": "Extinct",
"E": "Endangered",
"PE": "Extinct in the wild",
"CR": "Critically endangered",
"V": "Vulnerable",
"NT": "Near threatened wildlife",
"SL": "Special least concern",
"C": "Least concern wildlife",
"I": "International wildlife" 
}
text = data['status'] 
a = replace_all(text, codes)
data['status']  = a

<ipython-input-35-896616eea62f>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['status']  = a

In [36]:
codes = {
"EX" : "Extinct",
"WX" : "Extinct in the wild", 
"CE" : "Critically endangered", 
"E" : "Endangered", 
"V" : "Vulnerable",
"CD" : "Conservation dependent"
}
text = data['EPBCstatus'] 
b = replace_all(text, codes)
data['EPBCstatus']  = b

<ipython-input-36-09463f9060c2>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['EPBCstatus']  = b

In [37]:
codes = {
"Q" : "Queensland endemic",
"QA" : "Australian endemic", 
"QI" : "Naturally occurs in Queensland and overseas", 
"QAI" : "Naturally occurs in Australia and overseas", 
"V" : "Native to Queensland",
"U" : "Native to Queensland - endemicity not defined",
"II" : "Naturalised from overseas",
"IA" : "Naturalised from elsewhere in Australia",
"IU" : "Naturalised species - origin not defined",
"VA" : "Australian vagrant",
"VI" : "International vagrant",
"VU" : "vagrant - origin not defined"
}
text = data['endemicity'] 
c = replace_all(text, codes)
data['endemicity']  = c

<ipython-input-37-a23d253b8610>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['endemicity']  = c

In [38]:

codes = {
"Y" : "Yes",
"N" : "No"
}
text = data['confidential'] 
d = replace_all(text, codes)
data['confidential']  = d

<ipython-input-38-4e43ec5d92c8>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['confidential']  = d

In [39]:

codes = {
"Y" : "Yes",
"N" : "No"
}
text = data['conservationSignificant'] 
d = replace_all(text, codes)
data['conservationSignificant']  = d

<ipython-input-39-e018da3f0c67>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['conservationSignificant']  = d

In [40]:
data

,taxonID,kingdom,class,family,scientificName,vernacularName,scientificNameAuthorship,status,EPBCstatus,conservationSignificant,confidential,endemicity
0,706,animals,amphibians,Limnodynastidae,Adelotus brevis,tusked frog,"(Günther, 1863)",Vulnerable,NaN,Yes,No,Australian endemic
1,690,animals,amphibians,Limnodynastidae,Lechriodus fletcheri,black soled frog,"(Boulenger, 1890)",Least concern wildlife,NaN,No,No,Australian endemic
2,677,animals,amphibians,Limnodynastidae,Limnodynastes convexiusculus,marbled frog,"(MacLeay, 1877)",Least concern wildlife,NaN,No,No,Naturally occurs in Australia and overseas
3,678,animals,amphibians,Limnodynastidae,Limnodynastes dumerilii,grey bellied pobblebonk,"Peters, 1863",Least concern wildlife,NaN,No,No,Australian endemic
4,679,animals,amphibians,Limnodynastidae,Limnodynastes fletcheri,barking frog,"Boulenger, 1888",Least concern wildlife,NaN,No,No,Australian endemic
...,...,...,...,...,...,...,...,...,...,...,...,...
21752,25858,protozoans,slime molds,Physaraceae,Fuligo septica,NaN,(L.) F.H.Wigg.,Least concern wildlife,NaN,No,No,Queensland endemic
21753,34854,protozoans,slime molds,Stemonitidaceae,Comatricha pulchella,NaN,(Bab.) Rostaf.,Least concern wildlife,NaN,No,No,Queensland endemic
21754,27732,protozoans,slime molds,Stemonitidaceae,Stemonitis splendens,NaN,Rostaf.,Least concern wildlife,NaN,No,No,Queensland endemic
21755,41204,protozoans,slime molds,Trichiidae,Hemitrichia serpula,NaN,(Scop.) Rostaf.,Least concern wildlife,NaN,No,No,Queensland endemic
21756,34033,protozoans,slime molds,Tubiferaceae,Lycogala epidendrum,NaN,(L.) Fr.,Least concern wildlife,NaN,No,No,Queensland endemic

In [41]:
data.to_csv('/conservational-species-QLD.csv',index = False,encoding='utf-8-sig')